/// Flutter icons IotAppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IotAppIcons
///      fonts:
///       - asset: fonts/IotAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IotAppIcons {
  IotAppIcons._();

  static const _kFontFam = 'IotAppIcons';
  static const String? _kFontPkg = null;

  static const IconData accountant = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData auto_report = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compose_msp = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confirm = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_reports = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iot = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_vbsp = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData msp = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData query = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_doc = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xebaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
